import logging
import os

from fastapi import APIRouter

router = APIRouter(prefix="/api/mail", tags=["mail"])
logger = logging.getLogger("dashboard_backend")

_MOCK_DELETED = 42

# Gmail cleanup queries — matches Gmail's built-in bulk categories
_CLEANUP_QUERIES = [
    "category:promotions",
    "category:social",
    "category:updates",
    "category:forums",
]


def _get_gmail_service():
    """
    Returns an authenticated Gmail API service using stored OAuth2 token.
    Requires:
      GMAIL_TOKEN_FILE   — path to token.json (generated by OAuth2 flow)
    Falls back to None when unconfigured so the mock path runs instead.
    """
    token_file = os.getenv("GMAIL_TOKEN_FILE", "backend/gmail_token.json")
    if not os.path.exists(token_file):
        return None
    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build

        scopes = ["https://www.googleapis.com/auth/gmail.modify"]
        creds = Credentials.from_authorized_user_file(token_file, scopes)
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        return build("gmail", "v1", credentials=creds)
    except Exception as e:
        logger.error(f"Gmail service init error: {e}")
        return None


@router.post("/cleanup")
async def cleanup_promotions() -> dict:
    """Move all promotional, social, updates, and forum emails to trash."""
    service = _get_gmail_service()

    if service:
        try:
            deleted = 0
            for query in _CLEANUP_QUERIES:
                result = (
                    service.users().messages().list(userId="me", q=query, maxResults=500).execute()
                )
                messages = result.get("messages", [])
                if messages:
                    ids = [m["id"] for m in messages]
                    service.users().messages().batchModify(
                        userId="me",
                        body={"ids": ids, "addLabelIds": ["TRASH"], "removeLabelIds": []},
                    ).execute()
                    deleted += len(ids)
            return {"mode": "live", "deleted": deleted}
        except Exception as e:
            logger.error(f"Gmail cleanup error: {e}")

    logger.info("Gmail token not configured — returning mock cleanup response")
    return {"mode": "mock", "deleted": _MOCK_DELETED}
